version: "3.9"

services:
  lab04-database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/seed.js:/docker-entrypoint-initdb.d/seed.js

  lab04-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://lab04-database:27017/lab04
    ports:
      - "3001:3001"
    depends_on:
      - lab04-database
